---
title: "Final Exam - Econometrics I"
author: "Gustavo Henrique & Bruno Tonholo"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: sandstone
    toc: TRUE
    toc_float: TRUE
---

# Question 1
## Loading needed packages
```{r}
pacman::p_load(tidyverse)
```

## Importing and cleaning ppebase
```{r}
ppe = read.csv("progresa_policy_evaluation.csv") %>% 
  arrange(id_hogar) %>% 
  mutate(treat = ifelse(pobreden == "1", 1, 0),
         y_diff = y_post - y_baseline)
```

## Item (a)
Model without covariates
```{r}
model1 = lm(y_post ~ treat,
            data = ppe)
summary(model1)
```
Model with covariates
```{r}
model2 = lm(y_post ~ treat + age_baseline + sex_baseline,
            data = ppe)
summary(model2)
```

## Item (b)
Model without covariates
```{r}
model3 = lm(y_diff ~ treat,
            data = ppe)
summary(model3)
```

Model without covariates
```{r}
model4 = lm(y_diff ~ treat + age_baseline + sex_baseline,
            data = ppe)
summary(model4)
```

## Item (c)
```{r}
# Centralizing the running variable
ppe = ppe %>% 
  mutate(yycali_97_centered = yycali_97 - cut,
         const = 1)

# Corrected Silverman bandwidth estimator
silverman_bandwidth = function(X) {
  n = length(X)
  h = 2.345*n^(-1/5)*sd(X)
  return(h)
}
bw_silverman = silverman_bandwidth(ppe$yycali_97)

# Defining the Epanechnikov kernel and the indicator functions
epanechnikov_kernel <- function(u) {
  k = ifelse(abs(u) <= 1, 0.75*(1 - u^2), 0)
  return(k)
}

# Defining variables
X1 = as.matrix(ppe %>% 
  filter(treat == 1) %>% 
  select(const, yycali_97_centered))
y1 = ppe%>% 
  filter(treat == 1) %>% 
  select(y_post) %>% 
  pull()
X0 = as.matrix(ppe %>% 
  filter(treat == 0) %>% 
  select(const, yycali_97_centered))
y0 = ppe%>% 
  filter(treat == 0) %>% 
  select(y_post) %>% 
  pull()
u1 = (X1[, 2])/bw_silverman
u0 = (X0[, 2])/bw_silverman

# Calculating kernel weightings
w1 = diag(epanechnikov_kernel(u1))
w0 = diag(epanechnikov_kernel(u0))

# Calculating beta 1
beta1 = solve(t(X1)%*%w1%*%X1)%*%(t(X1)%*%w1%*%y1)

# Calculating beta 0
beta0 = solve(t(X0)%*%w0%*%X0)%*%(t(X0)%*%w0%*%y0)

# Calculating beta RDD
beta_rdd = beta1 - beta0
beta_rdd
```

(i) Increasing h
```{r}
bw_i = bw_silverman*1.5
u1_i = (X1[, 2])/bw_i
u0_i = (X0[, 2])/bw_i

# Calculating kernel weightings
w1_i = diag(epanechnikov_kernel(u1_i))
w0_i = diag(epanechnikov_kernel(u0_i))

# Calculating beta 1
beta1_i = solve(t(X1)%*%w1_i%*%X1)%*%(t(X1)%*%w1_i%*%y1)

# Calculating beta 0
beta0_i = solve(t(X0)%*%w0_i%*%X0)%*%(t(X0)%*%w0_i%*%y0)

# Calculating beta RDD
beta_rdd_i = beta1_i - beta0_i
beta_rdd_i
```

(ii) Decreasing h
```{r}
bw_d = bw_silverman*0.5
u1_d = (X1[, 2])/bw_d
u0_d = (X0[, 2])/bw_d

# Calculating kernel weightings
w1_d = diag(epanechnikov_kernel(u1_d))
w0_d = diag(epanechnikov_kernel(u0_d))

# Calculating beta 1
beta1_d = solve(t(X1)%*%w1_d%*%X1)%*%(t(X1)%*%w1_d%*%y1)

# Calculating beta 0
beta0_d = solve(t(X0)%*%w0_d%*%X0)%*%(t(X0)%*%w0_d%*%y0)

# Calculating beta RDD
beta_rdd_d = beta1_d - beta0_d
beta_rdd_d
```
Printing results
```{r}
results = data.frame(
  Bandwidth = c("Original", "Increased", "Decreased"),
  Constant = c(beta_rdd[1], beta_rdd_i[1], beta_rdd_d[1]),
  Beta_RDD = c(beta_rdd[2], beta_rdd_i[2], beta_rdd_d[2])
)
results
```
# Question 2
## Loading needed packages
```{r}
pacman::p_load(purrr,
               EnvStats,
               dplyr)
```

## Item (b)
```{r}
beta_0 <- 0.5
beta_1 <- 0.4

mi = log(25/(sqrt(25+3)))
sigma = log(1+(3/25))

set.seed(123)

#Creating a hundred 500 size and 1000 size sample data sets:

dataset <- function(N){
  x <- rlnorm(N, meanlog = mi, sdlog = sqrt(sigma))
  e_0 <- revd(N, location = 0, scale = 1)
  e_1 <- revd(N, location = 0, scale = 1)
  u <- beta_0 + beta_1*x + (e_1-e_0)
  d <- 1*(u >= 0)
  ds <- matrix(data = c(d, x), nrow = N, ncol = 2)
}

N500 <- rep(500, 100)

datasets_500 <- map(N500, dataset)

N1000 <- rep(1000, 100)

datasets_1000 <- map(N1000, dataset)
```


## Item (c)
```{r}
subfinal_f <- function(data, beta, S){
  d<- data[,1]
  
  x <- data[,2]
  
  N <- length(x)
  
  datasets_mm <- list()
  means <- c()
  covs <- c()
  
  for(i in 1:S){
    
    e_0 <- revd(N, location = 0, scale = 1)
    e_1 <- revd(N, location = 0, scale = 1)
    
    u <- beta[1] + beta[2]*x +(e_1-e_0)
    
    decision <- if_else(u>=0,1,0)
    
    datasets_mm[[i]] <- matrix(data = c(decision, x), nrow = N, ncol = 2)
    
    means[i] <- mean(datasets_mm[[i]][,1])
    
    covs[i] <- cov(x, datasets_mm[[i]][,1])
  }
  
  m <- matrix(c(means,covs), nrow = S, ncol = 2)
  
  mm <- colMeans(m)
  
  xx <- c(mean(data[,1]),cov(x,d))
  
  beta_teste <- t(xx - mm) %*% (xx - mm)
  
}

######Size =500 and S=30:
data_beta500_30 <-list()
final_beta500_30 <-list()

for(i in 1:100){
  data_beta500_30[[i]] <- optim(c(0.4, 0.3), subfinal_f, method = 'BFGS',
                                data = datasets_500[[i]],
                                S = 30)
  
  final_beta500_30[[i]]<-data_beta500_30[[i]]$par  
}

final_beta500_30 <- do.call(rbind, final_beta500_30)

mean_beta500_30 <- c(mean(final_beta500_30[,1]), mean(final_beta500_30[,2]))

mean_beta500_30

var_beta500_30 <- c(var(final_beta500_30[,1]), var(final_beta500_30[,2]))

var_beta500_30

mse_beta500_30 <- c(mean((beta_0 - final_beta500_30[,1])^2), mean((beta_1 - final_beta500_30[,2])^2))


######Size =1000 and S=30:
data_beta1000_30 <-list()
final_beta1000_30 <-list()

for(i in 1:100){
  data_beta1000_30[[i]] <- optim(c(0.4, 0.3), subfinal_f, method = 'BFGS',
                                 data = datasets_1000[[i]],
                                 S = 30)
  
  final_beta1000_30[[i]]<-data_beta1000_30[[i]]$par  
}


final_beta1000_30 <- do.call(rbind, final_beta1000_30)

mean_beta1000_30 <- c(mean(final_beta1000_30[,1]), mean(final_beta1000_30[,2]))

mean_beta1000_30

var_beta1000_30 <- c(var(final_beta1000_30[,1]), var(final_beta1000_30[,2]))

var_beta1000_30

mse_beta1000_30 <- c(mean((beta_0 - final_beta1000_30[,1])^2), mean((beta_1 - final_beta1000_30[,2])^2))
```

## Item (d)
```{r}
######Size =500 and S=100:

data_beta500_100 <-list()
final_beta500_100 <-list()

for(i in 1:100){
  data_beta500_100[[i]] <- optim(c(0.4, 0.3), subfinal_f, method = 'BFGS',
                                 data = datasets_500[[i]],
                                 S = 100)
  
  final_beta500_100[[i]]<-data_beta500_100[[i]]$par  
}


final_beta500_100 <- do.call(rbind, final_beta500_100)

mean_beta500_100 <- c(mean(final_beta500_100[,1]), mean(final_beta500_100[,2]))

mean_beta500_100

var_beta500_100 <- c(var(final_beta500_100[,1]), var(final_beta500_100[,2]))

var_beta500_100

mse_beta500_100 <- c(mean((beta_0 - final_beta500_100[,1])^2), mean((beta_1 - final_beta500_100[,2])^2))


######Size =1000 and S=100:
data_beta1000_100 <-list()
final_beta1000_100 <-list()

for(i in 1:100){
  data_beta1000_100[[i]] <- optim(c(0.4, 0.3), subfinal_f, method = 'BFGS',
                                  data = datasets_1000[[i]],
                                  S = 100)
  
  final_beta1000_100[[i]]<-data_beta1000_100[[i]]$par  
}


final_beta1000_100 <- do.call(rbind, final_beta1000_100)

mean_beta1000_100 <- c(mean(final_beta1000_100[,1]), mean(final_beta1000_100[,2]))

mean_beta1000_100

var_beta1000_100 <- c(var(final_beta1000_100[,1]), var(final_beta1000_100[,2]))

var_beta1000_100

mse_beta1000_100 <- c(mean((beta_0 - final_beta1000_100[,1])^2), mean((beta_1 - final_beta1000_100[,2])^2))
```

## Item (f)
```{r}
delta <- 0.2
num_datasets <- 100
treatment_datasets <- sample(1:num_datasets, 50)

within_effects <- numeric(length = 50)
between_effects <- numeric(length = num_datasets)

for (i in 1:num_datasets) {
  data <- datasets_1000[[i]]
  
  bottom_quartile <- data[data[, 2] <= quantile(data[, 2], 0.25), ]
  x <- bottom_quartile[, 2]
  d <- bottom_quartile[, 1]
  
  if (i %in% treatment_datasets) {
    x_treated <- x * (1 + delta)
    
    u_treated <- alfa_0 + alfa_1 * x_treated
    d_treated <- ifelse(u_treated >= 0, 1, 0)
    
    u_original <- alfa_0 + alfa_1 * x
    d_original <- ifelse(u_original >= 0, 1, 0)
    
    within_effects[i] <- mean(d_treated) - mean(d_original)
  } else {
    d_treated <- d
  }
  
  between_effects[i] <- mean(d_treated) - mean(d)
}

within_effect_mean <- mean(within_effects, na.rm = TRUE)
between_effect_mean <- mean(between_effects, na.rm = TRUE)

cat("Average Within-Household Treatment Effect:", within_effect_mean, "\n")
cat("Average Between-Household Treatment Effect:", between_effect_mean, "\n")

```