---
title: "Replication Project"
author: "Gustavo Henrique & Bruno Tonholo"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Step 1: Importing needed packages

```{r}
pacman::p_load("tidyverse",
               "haven",
               "estimatr",
               "stats",
               "fixest",
               "rdrobust",
               "rddensity",
               "rdd",
               "miceadds",
               "rddtools",
               "here",
               "cowplot",
               "scales")
```

## Step 2: Loading databases

```{r}
df_mun = read_dta(here("replication_project/data", "munic.dta"))
df_state = read_dta(here("replication_project/data", "state.dta"))
df_yearly = read_dta(here("replication_project/data", "yearly.dta"))
```

## Step 3: Cleaning databases

```{r}
# Define variables
munic = df_mun %>%
  mutate(
    dep = voters96 - 40500,
    treat = ifelse(dep > 0, 1, 0),
    deptreat = dep * treat,
    bw = ifelse(dep < 0, -dep, dep),
    ones = 1
  )

# Set binned variables
bins = seq(500, 200000, by = 4000)
munic = munic %>%
  mutate(bin_voters96 = cut(voters96, breaks = bins, right = FALSE, labels = FALSE) * 4000 + 2000) %>%
  group_by(bin_voters96) %>%
  mutate(
    bin_util94 = mean(r_util94, na.rm = TRUE),
    bin_util98 = mean(r_util98, na.rm = TRUE),
    bin_util02 = mean(r_util02, na.rm = TRUE),
    bin_attend = mean(attend, na.rm = TRUE),
    bin_regist = mean(regist, na.rm = TRUE),
    bin_obs = sum(ones)
  ) %>%
  ungroup()
```

## Step 4: Estimation

```{r}
# feols(r_util98 ~ treat + dep + deptreat,
#       data = df_mun %>% 
#         filter(bw < 11873),
#       vcov = "HC1")
# feols(attend ~ treat + dep + deptreat,
#       data = df_mun %>% 
#         filter(bw < 12438),
#       vcov = "HC1")
# feols(regist ~ treat + dep + deptreat,
#       data = df_mun %>% 
#         filter(bw < 15956),
#       vcov = "HC1")
# feols(r_util94 ~ treat + dep + deptreat,
#       data = df_mun %>% 
#         filter(bw < 17111),
#       vcov = "HC1")
# feols(r_util02 ~ treat + dep + deptreat,
#       data = df_mun %>% 
#         filter(bw < 17204),
#       vcov = "HC1")
# feols(c(r_util98, attend, regist, r_util94, r_util02) ~ treat + dep + deptreat,
#       data = df_mun %>% 
#         filter(bw < 10000),
#       vcov = "HC1")
# feols(c(r_util98, attend, regist, r_util94, r_util02) ~ treat + dep + deptreat,
#       data = df_mun %>% 
#         filter(bw < 5000),
#       vcov = "HC1")
```

## Step 5: Data visualization

```{r, warning=FALSE}
# Figure 2 - scatter plots with quadratic fits
plot_main1 = ggplot(munic %>% filter(voters96 < 100000, voters96 > 4500), aes(x = bin_voters96)) +
  geom_point(aes(y = bin_util94, x = bin_voters96 - 4000), shape = 15, size = 2.5, color = "green") +
  geom_point(aes(y = bin_util98, x = bin_voters96 - 4000), shape = 16, size = 2.5, color = "blue") +
  geom_point(aes(y = bin_util02, x = bin_voters96 - 4000), shape = 17, size = 2.5, color = "red") +
  stat_smooth(aes(x = voters96, y = r_util94), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "green", data = munic %>% filter(voters96 < 40500, voters96 > 5000)) +
  stat_smooth(aes(x = voters96, y = r_util94), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "green", data = munic %>% filter(voters96 < 100000, voters96 > 40500)) +
  stat_smooth(aes(x = voters96, y = r_util02), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "red", data = munic %>% filter(voters96 < 40500, voters96 > 5000)) +
  stat_smooth(aes(x = voters96, y = r_util02), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "red", data = munic %>% filter(voters96 < 100000, voters96 > 40500)) +
  stat_smooth(aes(x = voters96, y = r_util98), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "blue", data = munic %>% filter(voters96 < 40500, voters96 > 5000)) +
  stat_smooth(aes(x = voters96, y = r_util98), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "blue", data = munic %>% filter(voters96 < 100000, voters96 > 40500)) +
  geom_vline(xintercept = 40500) +
  labs(y = "", x = "Number of Registered Voters - 1996") +
  theme_minimal() +
  scale_x_continuous(limits = c(0, 100000), breaks = seq(0, 100000, by = 20000), labels = number_format(accuracy = 1, big.mark = "")) +
  scale_y_continuous(limits = c(0.525, 1), breaks = seq(0.6, 1, by = 0.1))

legend_plot1 = get_legend(ggplot(munic, aes(x = bin_voters96)) +
  geom_point(aes(y = bin_util94, color = "Valid Votes/Turnout - 1994 Election (Paper Only)"), shape = 15, size = 2.5) +
  geom_point(aes(y = bin_util98, color = "Valid Votes/Turnout - 1998 Election (Discontinuity)"), shape = 16, size = 2.5) +
  geom_point(aes(y = bin_util02, color = "Valid Votes/Turnout - 2002 Election (Electronic Only)"), shape = 17, size = 2.5) +
  scale_color_manual(values = c("green", "blue", "red")) +
  guides(color = guide_legend(title = NULL)) +
  theme_void())

final_plot1 = plot_grid(plot_main1, legend_plot1, ncol = 1, rel_heights = c(1, 0.2))

# Figure 3 - similar approach for bin_regist and bin_attend
plot_main2 = ggplot(munic %>% filter(voters96 < 100000, voters96 > 4500), aes(x = bin_voters96)) +
  geom_point(aes(y = bin_regist, x = bin_voters96 - 4000), shape = 16, size = 2.5, color = "green") +
  geom_point(aes(y = bin_attend, x = bin_voters96 - 4000), shape = 17, size = 2.5, color = "blue") +
  stat_smooth(aes(x = voters96, y = regist), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "green", data = munic %>% filter(voters96 < 40500, voters96 > 5000)) +
  stat_smooth(aes(x = voters96, y = regist), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "green", data = munic %>% filter(voters96 < 100000, voters96 > 40500)) +
  stat_smooth(aes(x = voters96, y = attend), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "blue", data = munic %>% filter(voters96 < 40500, voters96 > 5000)) +
  stat_smooth(aes(x = voters96, y = attend), method = "lm", formula = y ~ poly(x, 2), se = FALSE, color = "blue", data = munic %>% filter(voters96 < 100000, voters96 > 40500)) +
  geom_vline(xintercept = 40500) +
  labs(y = "", x = "Number of Registered Voters - 1996") +
  theme_minimal() +
  scale_x_continuous(limits = c(0, 100000), breaks = seq(0, 100000, by = 20000), labels = number_format(accuracy = 1, big.mark = "")) +
  scale_y_continuous(limits = c(0.525, 1), breaks = seq(0.6, 1, by = 0.1))

legend_plot2 = get_legend(ggplot(munic, aes(x = bin_voters96)) +
                            geom_point(aes(y = bin_regist, color = "Registered Voters/Total Population"), shape = 16, size = 2.5) +
                            geom_point(aes(y = bin_attend, color = "Turnout/Registered Voters"), shape = 17, size = 2.5) +
                            scale_color_manual(values = c("green", "blue")) +
                            guides(color = guide_legend(title = NULL)) +
                            theme_void())

final_plot2 = plot_grid(plot_main2, legend_plot2, ncol = 1, rel_heights = c(1, 0.2))
```
Printing the graphs
```{r}
# Figure 2
final_plot1
```
```{r}
# Figure 3
final_plot2
```


